% Auxiliary script to construct the sum of all the twitches generated by a
% signle neuron
% INPUT
%   - tspikesn (fro one neuron)
%   - Nspikesn (from one neuron)
% OUTPUT 
%   - Fn: Force corresponding to this neuron (sum of twitches)
Tcn = Tc(in); %contraction time for this neuron
 
T_ISI = Tcn./ISI_vec; %instantaneous normalized discharge rate
gnt = ones(1,Nspikesn); % gain of the force (varies with time) If it's small is 1
 
norm_sigm = (1-exp(-2.*(0.4).^3))./(0.4);
aux_sigm = (1-exp(-2.*(T_ISI).^3))./(T_ISI); gnt(T_ISI>0.4) = aux_sigm(T_ISI>0.4)./norm_sigm;%if it's bigger it follows a sigmoid
amp_fnt = gnt.*P(in)./Tcn; amp_fnt = amp_fnt';%aux variable: amplitude of the motor-unit impulse response per each spike
% now we have that each twitch (corresponding each to one spike) is a row;
aux_t = repmat(t, Nspikesn, 1) - repmat(tspikesn',1,Nt); % Each row corresponds to a time vector "displaced" by the firing instant of each spike
%aux_t = aux_t';
aux_texpt = aux_t.*exp(1-(aux_t./Tcn)); 
fnt = amp_fnt.*aux_texpt; %motor unit impulse response for each discharge already displaced
fnt(fnt<0) = 0;
%plot(fnt')
Fn = sum(fnt); %we sum the result of each twitch: this is for one neuron